# docker-compose.yml
services:
  web:
    image: php:8-apache
    ports:
      - 80:80
    volumes:
      - ./public_html:/var/www/public_html
# docker --version
# docker compose up -d
# docker compose down
